### ISSUE TITLE
Crash when pressing space when viewing grid

### ISSUE THREAD

**Issue by YTCuber** [JellyWX/Minesweeper#2]
**Reconstruct:**
run "python3 main.py"
press "Play"
make a mistake
press "View grid"
then press the space key

This is what happens:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "main.py", line 183, in run
    self.func()
  File "main.py", line 51, in process
    i.key_hit(keys)
AttributeError: 'Grid' object has no attribute 'key_hit'
```

When running ./main, this happens:
```
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    for e in gui.event():
AttributeError: 'Grid' object has no attribute 'key_hit'
Failed to execute script main
```

**Comment by JellyWX** [comment]
Many thanks! For now, just hitting backspace should work to close the grid. ill fix this in the meantime

**Comment by JellyWX** [comment]
Should be patched now. Confirm it is working and then I'll close the issue

**Comment by YTCuber** [comment]
It looks fixed for me.
